In [2]:
# import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import MaxPool2D,AveragePooling2D,Input
# from helper import plot_pool




In [5]:
x = tf.constant([[1., 2., 3.],
                 [4., 5., 6.],
                 [7., 8., 9.]])
x = tf.reshape(x, [1, 3, 3, 1])
avg_pool_2d = tf.keras.layers.AveragePooling2D(pool_size=(2, 2),
   strides=(1, 1), padding='valid')
avg_pool_2d(x)



<tf.Tensor: shape=(1, 2, 2, 1), dtype=float32, numpy=
array([[[[3.],
         [4.]],

        [[6.],
         [7.]]]], dtype=float32)>

In [7]:
x = tf.constant([[1., 2., 3.],
                 [4., 5., 6.],
                 [7., 8., 9.]])
x = tf.reshape(x, [1, 3, 3, 1])

tf.keras.layers.AveragePooling2D((int(x.shape[1]), int(x.shape[2])))(x)

<tf.Tensor: shape=(1, 1, 1, 1), dtype=float32, numpy=array([[[[5.]]]], dtype=float32)>

In [21]:
# Create a range of values from 1 to 24
values = tf.range(1, 25, dtype=tf.float32)

# Reshape the values into the desired shape
x = tf.reshape(values, [-1, 2, 3, 4])

# Print the tensor
print(x)

print(x.shape[1])

tf.keras.layers.AveragePooling2D((int(x.shape[1]), int(x.shape[2])))(x)



tf.Tensor(
[[[[ 1.  2.  3.  4.]
   [ 5.  6.  7.  8.]
   [ 9. 10. 11. 12.]]

  [[13. 14. 15. 16.]
   [17. 18. 19. 20.]
   [21. 22. 23. 24.]]]], shape=(1, 2, 3, 4), dtype=float64)
2


<tf.Tensor: shape=(1, 1, 1, 4), dtype=float32, numpy=array([[[[11., 12., 13., 14.]]]], dtype=float32)>